<?php

namespace App\Policies;

use App\Models\Certificate;
use App\Models\User;
use Illuminate\Auth\Access\Response;

class CertificatePolicy
{
    /**
     * Determine whether the user can view any models.
     */
    public function viewAny(User $user): bool
    {
        // ADMIN can view all certificates, TEACHER can view certificates for their courses
        return in_array($user->role, ['ADMIN', 'TEACHER']);
    }

    /**
     * Determine whether the user can view the model.
     */
    public function view(User $user, Certificate $certificate): bool
    {
        // ADMIN can view any certificate
        if ($user->role === 'ADMIN') {
            return true;
        }

        // TEACHER can view certificates for their courses
        if ($user->role === 'TEACHER') {
            return $certificate->course->teacher_id === $user->id;
        }

        // STUDENT can view their own certificates
        if ($user->role === 'STUDENT') {
            return $certificate->student_id === $user->id;
        }

        return false;
    }

    /**
     * Determine whether the user can create models.
     */
    public function create(User $user): bool
    {
        // Certificates are typically auto-generated by the system
        // Only ADMIN should manually create certificates
        return $user->role === 'ADMIN';
    }

    /**
     * Determine whether the user can update the model.
     */
    public function update(User $user, Certificate $certificate): bool
    {
        // Only ADMIN can update certificates (they should be immutable once issued)
        return $user->role === 'ADMIN';
    }

    /**
     * Determine whether the user can delete the model.
     */
    public function delete(User $user, Certificate $certificate): bool
    {
        // Only ADMIN can revoke/delete certificates
        return $user->role === 'ADMIN';
    }

    /**
     * Determine whether the user can download the certificate.
     */
    public function download(User $user, Certificate $certificate): bool
    {
        // ADMIN can download any certificate
        if ($user->role === 'ADMIN') {
            return true;
        }

        // TEACHER can download certificates for their courses
        if ($user->role === 'TEACHER') {
            return $certificate->course->teacher_id === $user->id;
        }

        // STUDENT can download their own certificates
        if ($user->role === 'STUDENT') {
            return $certificate->student_id === $user->id;
        }

        return false;
    }

    /**
     * Determine whether the user can verify the certificate.
     */
    public function verify(User $user, Certificate $certificate): bool
    {
        // All authenticated users can verify certificates (public verification)
        return true;
    }

    /**
     * Determine whether the user can restore the model.
     */
    public function restore(User $user, Certificate $certificate): bool
    {
        return $user->role === 'ADMIN';
    }

    /**
     * Determine whether the user can permanently delete the model.
     */
    public function forceDelete(User $user, Certificate $certificate): bool
    {
        return $user->role === 'ADMIN';
    }
}
